"""empty message

Revision ID: 247a6902ef20
Revises: 5294cba78b9f
Create Date: 2024-01-03 02:03:56.979279

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '247a6902ef20'
down_revision = '5294cba78b9f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('planets', schema=None) as batch_op:
        batch_op.alter_column('population',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('planets', schema=None) as batch_op:
        batch_op.alter_column('population',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False)

    # ### end Alembic commands ###
